### ISSUE TITLE
개고생을 커피캣처럼 사이트에 올리게 해주세요

### ISSUE THREAD

**Issue by yoonjieun** [lazypic/web#5]
상단메뉴에 CoffeeCat 옆에 CatNDog 메뉴를 추가해서 커피캣과 같은 방식으로 개고생 웹툰을 올려서 정리하고 싶습니다.
커피캣과 동일하게 <<이전  다음>> 1화보기 메뉴가 필요하고
화살표로 이전화 다음화 이동이 가능했으면 좋겠습니다.

**Comment by khw7096** [comment]
오키~
